spring:
  application:
    name: one-payroll
  datasource:
    url: jdbc:postgresql://localhost:5432/tw_payroll
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  servlet:
    context-path: /tw-payroll-system/api

integration:
  payroll:
    submit-url: http://localhost:8080/tw-payroll-system/api/integration/payroll/submit

jwt:
  secret: "6Cqv7P0/Y62z5FbBg/WSx4GgT5l4zM9QzK2Jb8z47lU="
  issuer: one-payroll
  expiration: -1